# File: docker-compose.yml

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - "./services/users:/usr/src/app"
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=dev
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql+psycopg://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - users-db-data:/var/lib/postgresql/data

  client:
    build:
      context: ./services/client/
      dockerfile: Dockerfile

    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_APP_USERS_SERVICE_URL=http://localhost:8001
    depends_on:
      - users

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - "./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - users
      - client

volumes:
  users-db-data:
